//! `#[derive(Children)]` — generates a complete child-`NodeId` traversal for an
//! AST enum, so that no tree-walk can silently miss a child.
//!
//! The generated method:
//!
//! ```ignore
//! impl ExprNode {
//!     pub fn for_each_child<F: FnMut(NodeId)>(&self, f: &mut F) { ... }
//! }
//! ```
//!
//! A field counts as a child edge purely by its (syntactic) type:
//!
//! * `NodeId`            → `f(node)`
//! * `Option<NodeId>`    → `f(node)` when `Some`
//! * `Vec<NodeId>`       → `f(node)` for each element
//!
//! Every other field type (`u32`, `u16`, `bool`, operator enums, `Vec<(u32,u32)>`,
//! …) is treated as scalar payload and ignored. Because the set of children is
//! derived from the struct definition, adding a new child field automatically
//! includes it in every traversal — the class of "walker forgot a child" bugs
//! becomes impossible by construction.
//!
//! `NodeId` must be in scope at the derive site (it is, via the AST module's
//! `pub use … NodeId`).

use proc_macro::TokenStream;
use quote::quote;
use syn::{
    parse_macro_input, Data, DeriveInput, Fields, GenericArgument, PathArguments, Type,
};

/// How a struct field participates in child traversal.
enum Kind {
    /// Not a child edge (scalar payload).
    No,
    /// A `NodeId`.
    Direct,
    /// An `Option<NodeId>`.
    Opt,
    /// A `Vec<NodeId>`.
    Vec,
}

#[proc_macro_derive(Children)]
pub fn derive_children(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as DeriveInput);
    let name = &input.ident;

    let data = match &input.data {
        Data::Enum(d) => d,
        _ => {
            return syn::Error::new_spanned(&input, "Children can only be derived for enums")
                .to_compile_error()
                .into()
        }
    };

    let arms = data.variants.iter().map(|v| {
        let vname = &v.ident;
        match &v.fields {
            Fields::Unit => quote! { #name::#vname => {} },
            Fields::Named(fields) => named_arm(name, vname, fields),
            Fields::Unnamed(fields) => unnamed_arm(name, vname, fields),
        }
    });

    quote! {
        impl #name {
            /// Invoke `f` once per child `NodeId`, in field order.
            /// Generated by `#[derive(Children)]` — see `vb6-ast-derive`.
            pub fn for_each_child<F: FnMut(NodeId)>(&self, f: &mut F) {
                match self {
                    #(#arms),*
                }
            }
        }
    }
    .into()
}

/// Build the match arm for a struct-like (named-field) variant.
fn named_arm(
    name: &syn::Ident,
    vname: &syn::Ident,
    fields: &syn::FieldsNamed,
) -> proc_macro2::TokenStream {
    let mut binds = Vec::new();
    let mut body = Vec::new();
    for fld in &fields.named {
        let ident = fld.ident.as_ref().unwrap();
        let pat = quote! { #ident };
        push_field(&mut binds, &mut body, classify(&fld.ty), &pat, false);
    }
    if binds.is_empty() {
        quote! { #name::#vname { .. } => {} }
    } else {
        quote! { #name::#vname { #(#binds),* , .. } => { #(#body)* } }
    }
}

/// Build the match arm for a tuple-like (unnamed-field) variant.
fn unnamed_arm(
    name: &syn::Ident,
    vname: &syn::Ident,
    fields: &syn::FieldsUnnamed,
) -> proc_macro2::TokenStream {
    let mut binds = Vec::new();
    let mut body = Vec::new();
    for (i, fld) in fields.unnamed.iter().enumerate() {
        let var = syn::Ident::new(&format!("__f{i}"), proc_macro2::Span::call_site());
        let pat = quote! { #var };
        push_field(&mut binds, &mut body, classify(&fld.ty), &pat, true);
    }
    quote! { #name::#vname( #(#binds),* ) => { #(#body)* } }
}

/// Append the binding pattern and traversal body for one field, given how it is
/// classified. `positional` controls the ignored-field binding: tuple variants
/// must bind every position (`_`), struct variants elide via `..`.
fn push_field(
    binds: &mut Vec<proc_macro2::TokenStream>,
    body: &mut Vec<proc_macro2::TokenStream>,
    kind: Kind,
    pat: &proc_macro2::TokenStream,
    positional: bool,
) {
    match kind {
        Kind::No => {
            if positional {
                binds.push(quote! { _ });
            }
        }
        Kind::Direct => {
            binds.push(quote! { #pat });
            body.push(quote! { f(*#pat); });
        }
        Kind::Opt => {
            binds.push(quote! { #pat });
            body.push(quote! {
                if let ::core::option::Option::Some(__c) = #pat { f(*__c); }
            });
        }
        Kind::Vec => {
            binds.push(quote! { #pat });
            body.push(quote! { for __c in #pat { f(*__c); } });
        }
    }
}

/// Classify a field type as a child edge by its outermost path segment.
fn classify(ty: &Type) -> Kind {
    let Type::Path(tp) = ty else { return Kind::No };
    let Some(seg) = tp.path.segments.last() else { return Kind::No };
    match seg.ident.to_string().as_str() {
        "NodeId" => Kind::Direct,
        "Option" if inner_is_nodeid(&seg.arguments) => Kind::Opt,
        "Vec" if inner_is_nodeid(&seg.arguments) => Kind::Vec,
        _ => Kind::No,
    }
}

/// True when angle-bracketed args are exactly `<NodeId>`.
fn inner_is_nodeid(args: &PathArguments) -> bool {
    let PathArguments::AngleBracketed(ab) = args else { return false };
    match ab.args.first() {
        Some(GenericArgument::Type(Type::Path(tp))) => {
            tp.path.segments.last().is_some_and(|s| s.ident == "NodeId")
        }
        _ => false,
    }
}
